[package]
name = "workshop"
version = "0.1.0"
edition = "2023_01"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.9.2"
kill_switch = { git = "https://github.com/starknet-edu/kill-switch" }

[[target.starknet-contract]]
casm = true
build-external-contracts = ["kill_switch::KillSwitch"]

[dev-dependencies]
snforge_std = "0.35.0"

[scripts]
test = "snforge test"
